"""Asynchronous web crawler built on asyncio and aiohttp."""

from crawler.advanced import AdvancedCrawler
from crawler.circuit_breaker import BreakerCall, CircuitBreaker, CircuitState
from crawler.client import AsyncCrawler
from crawler.config import CrawlerConfig, load_config, load_urls
from crawler.distributed import PostgresFrontier
from crawler.exceptions import (
    CertificateError,
    CircuitOpenError,
    ConfigError,
    CrawlerClosedError,
    DNSError,
    FetchError,
    FetchTimeoutError,
    FrontierError,
    HostHeldBackError,
    HTTPStatusError,
    InvalidURLError,
    JobError,
    NetworkError,
    NoProxyError,
    PageTooLargeError,
    ParseError,
    PermanentError,
    PermanentHTTPError,
    ProxyError,
    ProxyNetworkError,
    RenderError,
    RenderTimeoutError,
    RobotsDisallowedError,
    RobotsUnreachableError,
    SitemapError,
    StorageError,
    TooManyRedirectsError,
    TransientError,
    TransientHTTPError,
    UnexpectedError,
    error_kind,
)
from crawler.filters import UrlFilter
from crawler.frontier import (
    Admission,
    Frontier,
    FrontierPage,
    FrontierStats,
    GivenUp,
    HostFailures,
    MemoryFrontier,
    Outcome,
    UnsavedPage,
)
from crawler.logging_setup import configure_logging
from crawler.models import (
    CircuitStats,
    CrawlStats,
    DomainRate,
    ErrorStats,
    FetchResult,
    PageRecord,
    ParsedPage,
    ProxyStats,
    RateStats,
    RenderStats,
)
from crawler.parser import HTMLParser
from crawler.progress import Progress, ProgressTracker, format_progress, show_progress
from crawler.proxy import Proxy, ProxyPool
from crawler.queue import CrawlerQueue
from crawler.rate_limiter import RateLimiter
from crawler.rendering import Rendering
from crawler.retry import RetryRule, RetryStrategy
from crawler.robots import RobotsParser, RobotsRules, product_token
from crawler.semaphores import SemaphoreManager
from crawler.session import load_cookies_file, make_cookie, save_cookies_file
from crawler.sitemap import SitemapParser
from crawler.stats import CrawlerStats
from crawler.storage import (
    CompositeStorage,
    CSVStorage,
    DatabaseDriver,
    DatabaseStorage,
    DataStorage,
    JSONStorage,
    PostgresStorage,
    SQLiteStorage,
    register_database,
    storage_from_env,
    storage_from_output,
    storage_from_url,
)
from crawler.urls import get_host, is_same_host, is_valid_http_url

__all__ = [
    "Admission",
    "AdvancedCrawler",
    "AsyncCrawler",
    "BreakerCall",
    "CSVStorage",
    "CertificateError",
    "CircuitBreaker",
    "CircuitOpenError",
    "CircuitState",
    "CircuitStats",
    "CompositeStorage",
    "ConfigError",
    "CrawlStats",
    "CrawlerClosedError",
    "CrawlerConfig",
    "CrawlerQueue",
    "CrawlerStats",
    "DNSError",
    "DataStorage",
    "DatabaseDriver",
    "DatabaseStorage",
    "DomainRate",
    "ErrorStats",
    "FetchError",
    "FetchResult",
    "FetchTimeoutError",
    "Frontier",
    "FrontierError",
    "FrontierPage",
    "FrontierStats",
    "GivenUp",
    "HTMLParser",
    "HTTPStatusError",
    "HostFailures",
    "HostHeldBackError",
    "InvalidURLError",
    "JSONStorage",
    "JobError",
    "MemoryFrontier",
    "NetworkError",
    "NoProxyError",
    "Outcome",
    "PageRecord",
    "PageTooLargeError",
    "ParseError",
    "ParsedPage",
    "PermanentError",
    "PermanentHTTPError",
    "PostgresFrontier",
    "PostgresStorage",
    "Progress",
    "ProgressTracker",
    "Proxy",
    "ProxyError",
    "ProxyNetworkError",
    "ProxyPool",
    "ProxyStats",
    "RateLimiter",
    "RateStats",
    "RenderError",
    "RenderStats",
    "RenderTimeoutError",
    "Rendering",
    "RetryRule",
    "RetryStrategy",
    "RobotsDisallowedError",
    "RobotsParser",
    "RobotsRules",
    "RobotsUnreachableError",
    "SQLiteStorage",
    "SemaphoreManager",
    "SitemapError",
    "SitemapParser",
    "StorageError",
    "TooManyRedirectsError",
    "TransientError",
    "TransientHTTPError",
    "UnexpectedError",
    "UnsavedPage",
    "UrlFilter",
    "configure_logging",
    "error_kind",
    "format_progress",
    "get_host",
    "is_same_host",
    "is_valid_http_url",
    "load_config",
    "load_cookies_file",
    "load_urls",
    "make_cookie",
    "product_token",
    "register_database",
    "save_cookies_file",
    "show_progress",
    "storage_from_env",
    "storage_from_output",
    "storage_from_url",
]
